[2024-09-17 19:59:04,287] ERROR log_exception() L1449 Exception on /all_familys [GET] - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabia\Documents\GitHub\pos-fullstack\Sprint03\app-back\app.py", line 279, in get_familys
    family = session.query(Family).all()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\query.py", line 2673, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2237, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 2106, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\orm\session.py", line 1189, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 3278, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\engine\base.py", line 3302, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\sqlalchemy\pool\impl.py", line 168, in _do_get
    raise exc.TimeoutError(
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
[2024-09-17 19:59:04,298] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 19:59:04] "[35m[1mGET /all_familys HTTP/1.1[0m" 500 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 19:59:04,896] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 19:59:04] "GET /membros HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 19:59:04,897] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 19:59:04] "GET /all_familys HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 19:59:04,900] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 19:59:04] "GET /membros HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 19:59:04,900] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 19:59:04] "GET /all_familys HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 19:59:36,009] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 19:59:36] "GET /all_familys HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 19:59:36,010] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 19:59:36] "GET /membros HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 19:59:38,054] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 19:59:38] "GET /all_familys HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 19:59:38,054] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 19:59:38] "GET /membros HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 19:59:38,058] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 19:59:38] "GET /all_familys HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 19:59:38,059] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 19:59:38] "GET /membros HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 20:00:14,894] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 20:00:14] "GET /all_familys HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 20:00:14,896] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 20:00:14] "GET /membros HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 20:00:14,898] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 20:00:14] "GET /all_familys HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 20:00:14,900] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 20:00:14] "GET /membros HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 20:00:56,176] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 20:00:56] "GET /all_familys HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 20:00:56,180] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 20:00:56] "GET /all_familys HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 20:00:56,185] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 20:00:56] "GET /membros HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 20:00:56,187] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 20:00:56] "GET /membros HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 20:03:10,003] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 20:03:10] "GET /all_familys HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
[2024-09-17 20:03:10,003] INFO _log() L224  127.0.0.1 - - [17/Sep/2024 20:03:10] "GET /membros HTTP/1.1" 200 - - call_trace=C:\Users\fabia\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L224 
